# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Obj-C 2-3-2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Obj-C 2-3-2
	pod 'FMDB'
end
